#!/bin/bash

# Copyright 2020 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $(($RANDOM % 100)) -lt "$1" ]; then
    if [ $(($RANDOM % 2)) = 0 ]; then
        exit 0
    else
        exit 1
    fi
fi

if git merge-base --is-ancestor "$2" HEAD; then
  exit 1
else
  exit 0
fi
